const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("🚀 Deploying ZKP Contracts...\n");

  const [deployer] = await hre.ethers.getSigners();
  console.log("📝 Deploying with account:", deployer.address);

  const balance = await hre.ethers.provider.getBalance(deployer.address);
  console.log("💰 Account balance:", hre.ethers.formatEther(balance), "ETH\n");

  // 1. 部署 Verifier 合约
  console.log("1️⃣  Deploying Groth16Verifier...");
  const Verifier = await hre.ethers.getContractFactory("Groth16Verifier");
  const verifier = await Verifier.deploy();
  await verifier.waitForDeployment();
  const verifierAddress = await verifier.getAddress();
  console.log("✅ Groth16Verifier deployed to:", verifierAddress);

  // 2. 部署应用合约
  console.log("\n2️⃣  Deploying ZKPApplication...");
  const ZKPApp = await hre.ethers.getContractFactory("ZKPApplication");
  const zkpApp = await ZKPApp.deploy(verifierAddress);
  await zkpApp.waitForDeployment();
  const zkpAppAddress = await zkpApp.getAddress();
  console.log("✅ ZKPApplication deployed to:", zkpAppAddress);

  // 3. 保存部署信息
  const deploymentInfo = {
    network: hre.network.name,
    deployer: deployer.address,
    timestamp: new Date().toISOString(),
    contracts: {
      Groth16Verifier: verifierAddress,
      ZKPApplication: zkpAppAddress
    }
  };

  const deploymentPath = path.join(__dirname, "../deployments.json");
  fs.writeFileSync(deploymentPath, JSON.stringify(deploymentInfo, null, 2));
  console.log("\n💾 Deployment info saved to:", deploymentPath);

  // 4. 验证部署
  console.log("\n🔍 Verifying deployment...");
  const storedVerifier = await zkpApp.verifier();
  console.log("   ZKPApplication.verifier():", storedVerifier);
  console.log("   Match:", storedVerifier === verifierAddress ? "✅" : "❌");

  // 5. 输出摘要
  console.log("\n📊 Deployment Summary:");
  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  console.log(`Network:          ${hre.network.name}`);
  console.log(`Deployer:         ${deployer.address}`);
  console.log(`Verifier:         ${verifierAddress}`);
  console.log(`ZKP Application:  ${zkpAppAddress}`);
  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");

  // 6. 生成环境变量文件
  const envContent = `
# Generated by deploy.js at ${new Date().toISOString()}
NETWORK=${hre.network.name}
VERIFIER_ADDRESS=${verifierAddress}
ZKP_APPLICATION_ADDRESS=${zkpAppAddress}
`;

  const envPath = path.join(__dirname, "../.env.deployed");
  fs.writeFileSync(envPath, envContent.trim());
  console.log(`\n✅ Environment variables saved to: ${envPath}`);
  console.log("\n🎉 Deployment complete!\n");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("❌ Error:", error);
    process.exit(1);
  });
